### ISSUE TITLE
Where is the progarm "Cscatter "?

### ISSUE THREAD

**Issue by QiuLusssss** [peterkuma/microplastics2021#1]
Hello,I'm runing your projects( microplastics2021).I had a problem when I run the demo "run_cscatter".In demo there is a bash of linux which is  "Cscatter -w data/cscatter/wavelength -r data/cscatter/refract -l -t 0 -M -m 1 2 15e-6 1 -n 1 -P 1 -o data/cscatter/opt_prop_"$type_" -v".What I don't konw where is the "Cscatter ” program. How to get it.There are my question images on running demo.
![微信截图_20231126161555](https://github.com/peterkuma/microplastics2021/assets/91403156/b44d78f4-d2ce-4ea1-9f07-0f8d86027525)
![微信截图_20231126161730](https://github.com/peterkuma/microplastics2021/assets/91403156/88805369-51d5-4074-8285-042177a21401)
My E-mail is 1497986897@qq.com. Thank you!

**Comment by peterkuma** [comment]
Hi, as explained in the README, Cscatter is part of the radiation scheme SOCRATES developed at the Met Office. Unfortunately it has not been made publicly available, and that is why we cannot provide a link to the code in our repository. You could contact Dr James Manners at the Met Office (james.manners@metoffice.gov.uk) about access to SOCRATES.
